language: java
jdk: oraclejdk17

sudo: required

services:
  - docker

before_install:
  - docker build -f ./backend/Back-end/Dockerfile -t monzaj19/adoptitbackend .

script:
  - docker run -d monzaj19/adoptitbackend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push monzaj19/adoptitbackend

