language: java
jdk: oraclejdk17

sudo: required

services:
  - docker

if: branch = master

before_script:
  - wget http://chromedriver.storage.googleapis.com/99.0.4844.35/chromedriver_win32.zip
  - unzip chromedriver_win32.zip -d ./backend/Back-end/src/test/resources/drivers/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

  - docker build -f ./backend/Back-end/Dockerfile -t monzaj19/adoptitbackend .
  - docker build -f ./frontend/adoptit-front/Dockerfile -t monzaj19/adoptitfrontend .

script:
  - docker run -d monzaj19/adoptitbackend
  - docker run -d monzaj19/adoptitfrontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push monzaj19/adoptitbackend
  - docker push monzaj19/adoptitfrontend
