language: java
jdk: oraclejdk17

sudo: required
addons:
  chrome: stable

services:
  - docker

if: branch = master

install: true

script:
  - mvn -f ./backend/Back-end/pom.xml clean compile test

#before_script:
#  - mvn -f ./backend/Back-end/pom.xml test -B
#
#script:
#  - docker build -f ./backend/Back-end/Dockerfile -t monzaj19/adoptitbackend .
#  - docker build -f ./frontend/adoptit-front/Dockerfile -t monzaj19/adoptitfrontend .
##  - docker run -d monzaj19/adoptitbackend
##  - docker run -d monzaj19/adoptitfrontend

#after_success:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#
#  - docker push monzaj19/adoptitbackend
#  - docker push monzaj19/adoptitfrontend
