name: Docker Image Deployement to Azure Web App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
   DOCKER_IMAGE_NAME: 'adoptit'

jobs:

  build:
    runs-on: ubuntu-latest
    

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: change path
      run: cd /Back-end/
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}':v1
