# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - adoptit

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fd0b925500e14caabfb5fd6a9c304933 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c72a39c48c044b7da709e6b21db1b074 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fd0b925500e14caabfb5fd6a9c304933 }}/adoptit:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'adoptit'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8b3ae3a994a74c9bb24c2e57e36b6180 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fd0b925500e14caabfb5fd6a9c304933 }}/adoptit:${{ github.sha }}'